apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- deployment.yaml
- service.yaml

secretGenerator:
- name: mariadb-secret
  envs:
  - .env
