apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-app
spec:
  selector:
    matchLabels:
      app: challenge-app
  replicas: 2 # Update the replica count to 2
  template:
    spec:
      containers:
      - name: challenge-app
        resources:
          limits:
            cpu: "2000" # Raise CPU limit to 2000m (2 CPU cores)
            memory: "2048Mi" # Raise memory limit to 2048 MiB
          requests:
            cpu: "500" # Raise CPU request to 500m (0.5 CPU cores)
            memory: "256Mi"
